import React, { createContext, useState, useContext, useEffect } from 'react';

const LanguageContext = createContext();

const translations = {
  fr: {
    // Navbar
    discover: "Découvrir",
    myProfile: "Mon Profil CV",
    dashboard: "Tableau de Bord",
    logout: "Déconnexion",
    login: "Connexion",
    join: "Rejoindre Scoutini",
    player: "Joueur",
    scout: "Recruteur",
    club: "Club",
    academy: "Académie",
    admin: "Administrateur",
    
    // Home
    homePromo: "La plateforme n°1 du Scouting en Tunisie",
    homeHeroStart: "Deviens le Futur Talent du",
    homeHeroGreen: "Football Tunisien",
    homeHeroDesc: "Crée ton CV football numérique, publie tes vidéos highlights et fais-toi repérer par les plus grands clubs, académies et recruteurs en Tunisie.",
    homeSearchTalents: "Rechercher des Talents",
    homeWhyUse: "Pourquoi utiliser Scoutini ?",
    
    homeFeature1Title: "CV Football Numérique",
    homeFeature1Desc: "Renseigne ton poste, ton pied préféré, tes mensurations (taille/poids) et tes statistiques clés. Un vrai CV professionnel accessible en un clic.",
    
    homeFeature2Title: "Vidéos Highlights",
    homeFeature2Desc: "Upload tes meilleures actions, tes buts, tes dribbles et tes séances d'entraînement pour montrer concrètement ton talent et tes skills.",
    
    homeFeature3Title: "Scouting Direct",
    homeFeature3Desc: "Les scouts, académies et clubs tunisiens font des recherches avancées par critères précis pour te proposer des demandes d'essai physiques.",
    
    homeSectionTitle: "Rapprocher les Talents des Recruteurs en Tunisie",
    homeSectionDesc: "Que tu sois de Tunis, Sfax, Sousse, Bizerte, Nabeul ou de n'importe quel autre gouvernorat, Scoutini supprime les barrières géographiques et te donne une chance égale de réussir ta carrière professionnelle.",
    
    homeSectionPoint1Title: "100% Tunisien",
    homeSectionPoint1Desc: "Adapté à l'écosystème local et aux clubs de Ligue 1 & 2 en Tunisie.",
    
    homeSectionPoint2Title: "Vidéos de qualité",
    homeSectionPoint2Desc: "Un lecteur vidéo moderne pour analyser précisément le profil technique des joueurs.",
    
    homeFooter: "© 2026 Scoutini TN. Tous droits réservés. Conçu pour valoriser le football tunisien.",
    
    ctaCreateCV: "Créer mon CV Joueur",
    ctaManageCV: "Gérer mon CV Joueur",
    ctaDashboard: "Accéder à mon Tableau de Bord",
    
    // Auth Pages & Compliance
    loginTitle: "Connexion à Scoutini",
    registerTitle: "Créer un compte Scoutini",
    registerSub: "Choisissez votre profil et commencez l'aventure",
    email: "Adresse Email",
    password: "Mot de passe (min 6 caractères)",
    role: "Je suis un...",
    registerButton: "S'inscrire",
    loginButton: "Se connecter",
    noAccount: "Pas encore de compte ? S'inscrire",
    haveAccount: "Déjà un compte ? Se connecter",
    firstName: "Prénom",
    lastName: "Nom",
    fullName: "Nom Complet",
    organization: "Nom Structure / Club",
    dateOfBirth: "Date de naissance",
    parentInfoTitle: "Autorisation Parentale (Obligatoire pour les mineurs)",
    parentName: "Nom complet du parent / tuteur légal",
    parentNationalId: "N° CIN du parent",
    parentPhone: "Téléphone du parent",
    parentEmail: "Email du parent",
    parentalConsentCheck: "Je confirme sous serment avoir l'autorisation de mon parent/tuteur légal pour m'inscrire et partager mes informations.",
    termsCheck: "J'accepte les Conditions Générales d'Utilisation (CGU) et la Politique de Confidentialité de Scoutini.",
    acceptTermsStart: "J'accepte les ",
    acceptTermsAnd: " et la ",
    acceptTermsEnd: " de Scoutini.",
    cguLinkText: "Conditions Générales d'Utilisation",
    privacyLinkText: "Politique de Confidentialité",
    cguContent: "<h3>1. Acceptation des conditions</h3><p>En créant un compte sur Scoutini, vous acceptez d'être lié par les présentes CGU. Si vous êtes mineur de moins de 18 ans, vous déclarez avoir obtenu le consentement exprès de votre parent ou tuteur légal.</p><h3>2. Protection des mineurs</h3><p>La sécurité et la protection des mineurs sont au cœur de Scoutini. Il est strictement interdit à tout recruteur, club ou académie de tenter d'entrer en contact direct par des moyens externes ou inappropriés avec un mineur. Toutes les sollicitations officielles d'essais physiques doivent obligatoirement transiter par les coordonnées du parent/tuteur renseignées lors de l'inscription.</p><h3>3. Exactitude des informations</h3><p>Vous vous engagez à fournir des informations véridiques (identité, statistiques, date de naissance). Toute fausse déclaration pourra entraîner la suppression immédiate de votre compte.</p>",
    privacyContent: "<h3>1. Données collectées</h3><p>Nous collectons les données d'identification (nom, prénom, email, téléphone), les données de profil (date de naissance, taille, poids, club) et, pour les joueurs mineurs, les coordonnées du tuteur légal (nom, email, téléphone, numéro CIN).</p><h3>2. Finalité du traitement</h3><p>Les données parentales et des joueurs sont uniquement utilisées pour assurer la conformité légale et sécuriser les mises en relation dans le cadre de la détection de talents. Aucune donnée n'est partagée avec des tiers non autorisés.</p><h3>3. Droit d'accès et de suppression</h3><p>Conformément à la Loi Organique n° 2004-63 en Tunisie, les utilisateurs (et leurs parents si mineurs) disposent d'un droit d'accès, de rectification et de suppression de leurs données sur simple demande.</p>",
    
    // General
    loading: "Chargement...",
    back: "Retour",
    save: "Sauvegarder",
    cancel: "Annuler",
    tunisia: "Tunisie",

    // Login
    welcomeBack: "Bon retour !",
    loginSubtitle: "Connectez-vous pour accéder à votre compte Scoutini",
    emailField: "Adresse Email",
    passwordField: "Mot de passe",
    placeholderEmail: "Ex: joueur@scoutini.tn",
    signUpFreeLink: "S'inscrire gratuitement",
    invalidCredentialsError: "Identifiants incorrects.",
    dontHaveAccount: "Pas encore de compte ?",
    alreadyHaveAccount: "Déjà un compte ?",
    loginLink: "Se connecter",

    // Register
    rolePlayerDesc: "Créer mon CV",
    roleScoutDesc: "Détecteur pro",
    roleClubDesc: "Recruteur club",
    roleAcademyDesc: "Formation",
    placeholderFirstName: "Ex: Ahmed",
    placeholderLastName: "Ex: Ben Said",
    placeholderFullName: "Ex: Mohamed Gharbi",
    placeholderOrganization: "Ex: Scoutini Pro / EST",
    placeholderParentName: "Ex: Hedi Cherif",
    placeholderParentNationalId: "Ex: 08765432",
    placeholderParentPhone: "Ex: +216 98 765 432",
    placeholderParentEmail: "Ex: parent@email.com",
    placeholderEmailRegister: "Ex: contact@email.com",
    validationTermsError: "Vous devez accepter les Conditions Générales d'Utilisation et la Politique de Confidentialité.",
    validationParentalError: "Les informations d'autorisation parentale et leur confirmation sont obligatoires pour les mineurs.",
    registerError: "Erreur lors de l'inscription.",

    // SearchTalents
    searchTitle: "Détecter les Talents",
    searchSubtitle: "Recherchez et filtrez les jeunes joueurs de football en Tunisie par poste, région ou aptitudes.",
    searchPlaceholderName: "Rechercher par nom de joueur...",
    searchButton: "Rechercher",
    filterPosition: "Poste",
    filterRegion: "Région (Gouvernorat)",
    filterFoot: "Pied préféré",
    filterAllPositions: "Tous les postes",
    filterAllTunisia: "Toute la Tunisie",
    filterAll: "Tous",
    filterRightFoot: "Droitier",
    filterLeftFoot: "Gaucher",
    filterBothFeet: "Les Deux",
    resetFilters: "Réinitialiser",
    noPlayersFound: "Aucun joueur trouvé",
    noPlayersFoundDesc: "Essayez d'élargir vos filtres de recherche.",
    freeAgent: "Joueur Libre",
    statSpeed: "Vitesse",
    statTechnique: "Technique",
    viewCV: "Consulter le CV",

    // PlayerProfile
    loginToFavorite: "Veuillez vous connecter pour ajouter ce joueur aux favoris.",
    inFavorites: "Dans les Favoris",
    addFavorite: "Favori",
    inviteToTrial: "Inviter à un essai",
    bioAndPath: "Biographie & Parcours",
    noBio: "Le joueur n'a pas encore rédigé de biographie.",
    measurementsTitle: "Mensurations & Infos",
    height: "Taille",
    weight: "Poids",
    preferredFoot: "Pied",
    nationality: "Nationalité",
    bothFeetLabel: "Les 2",
    rightFootLabel: "Droit",
    leftFootLabel: "Gauche",
    bothFeetLabelLong: "Ambidextre",
    rightFootLabelLong: "Droitier",
    leftFootLabelLong: "Gaucher",
    noClub: "Sans club / Libre",
    dateNotSpecified: "Date non spécifiée",
    statsOnField: "Statistiques sur le terrain",
    matchesPlayed: "Matchs joués",
    goals: "Buts",
    assists: "Passes Décisives",
    performanceRadar: "Radar de Performance",
    videosHighlightsTitle: "Vidéos Highlights & Compilations",
    noVideos: "Aucune vidéo highlight publiée par ce joueur.",
    invitePlayerTitle: "Inviter {name} à un essai",
    invitePlayerDesc: "Envoyez une demande d'essai physique ou d'entraînement. Le joueur recevra votre message et pourra y répondre.",
    trialSentSuccess: "Demande d'essai envoyée !",
    playerNotified: "Le joueur a été notifié.",
    invitationMessage: "Message d'invitation",
    invitationPlaceholder: "Précisez la date, le lieu, et les détails de l'essai (ex: essai à Tunis le 30 juin)...",
    sendInvitation: "Envoyer l'invitation",
    playerNotFound: "Joueur non trouvé",
    playerNotFoundDesc: "Le profil de ce joueur n'existe pas ou a été supprimé.",
    backToSearch: "Retourner à la recherche",
    confirmRemoveFavorite: "Retirer ce joueur de vos favoris ?",

    // PlayerDashboard
    dashboardTitle: "Tableau de Bord Joueur",
    profileResume: "Résumé du profil",
    uploadPhoto: "Uploader",
    myDashboard: "Tableau de Bord",
    myFootballCV: "Mon CV Football",
    myStatistics: "Mes Statistiques",
    highlightVideos: "Vidéos Highlights",
    trialRequests: "Demandes d'Essais",
    cvInfoTitle: "Informations du CV Football",
    firstNameLabel: "Prénom",
    lastNameLabel: "Nom",
    dobLabel: "Date de Naissance",
    regionLabel: "Gouvernorat",
    selectOption: "Sélectionner",
    cityLabel: "Ville / Municipalité",
    cityPlaceholder: "Ex: La Marsa / Sfax Ouest",
    heightLabel: "Taille (cm)",
    heightPlaceholder: "Ex: 178",
    weightLabel: "Poids (kg)",
    weightPlaceholder: "Ex: 70",
    favPositionLabel: "Poste de prédilection",
    preferredFootLabel: "Pied préféré",
    currentClubLabel: "Club Actuel",
    currentClubPlaceholder: "Ex: CSS Jeunes (ou Aucun)",
    contactPhoneLabel: "Téléphone de contact",
    contactPhonePlaceholder: "Ex: +216 55 555 555",
    careerBioLabel: "Parcours & Bio",
    careerBioPlaceholder: "Parlez de votre parcours, de vos motivations...",
    saveCVButton: "Enregistrer le CV",
    skillsAndMatchesTitle: "Capacités & Matchs (Stats / 100)",
    physicalTechnicalTitle: "Profil Physique & Technique",
    attackingDefendingTitle: "Profil d'Attaque & Défense",
    matchStatsTitle: "Statistiques en Match",
    matchesPlayedLabel: "Matchs joués",
    goalsScoredLabel: "Buts marqués",
    assistsLabel: "Passes décisives",
    updateStatsButton: "Mettre à jour mes Stats",
    publishHighlightTitle: "Publier une vidéo Highlight",
    videoTitleLabel: "Titre de la vidéo",
    videoTitlePlaceholder: "Ex: But sur coup franc direct / Dribbles & Skills",
    videoCategoryLabel: "Catégorie",
    videoCategoryHIGHLIGHT: "Highlights généraux (Actions)",
    videoCategoryMATCH: "Match entier / Résumé",
    videoCategoryTRAINING: "Entraînement / Exercices physique",
    videoCategorySKILLS: "Dribbles & Gestes techniques",
    videoDescLabel: "Description / Contexte",
    videoDescPlaceholder: "Indiquez par exemple la minute de l'action, le nom de l'adversaire...",
    videoFileLabel: "Fichier Vidéo (MP4, Max 100 Mo)",
    publishVideoButton: "Publier sur Scoutini",
    myPublishedVideos: "Mes vidéos publiées",
    noVideosPublished: "Vous n'avez pas encore publié de vidéo highlight. Ajoutez-en une ci-dessus !",
    deleteVideoConfirm: "Voulez-vous vraiment supprimer cette vidéo highlight ?",
    avatarSuccess: "Photo de profil mise à jour avec succès !",
    cvSuccess: "Profil CV mis à jour avec succès !",
    statsSuccess: "Statistiques de performance enregistrées !",
    videoSuccess: "Vidéo highlight publiée !",
    videoDeletedSuccess: "Vidéo supprimée.",
    selectVideoFileError: "Veuillez sélectionner un fichier vidéo.",
    receivedTrialsTitle: "Demandes d'Essai Reçues",
    noReceivedTrials: "Vous n'avez reçu aucune demande d'essai pour le moment. Remplissez votre profil et publiez des vidéos pour vous faire repérer !",
    scoutVerifiedLabel: "Vérifié",
    noPresentationMessage: "Aucun message de présentation.",
    trialAcceptButton: "Accepter",
    trialDeclineButton: "Refuser",
    trialAcceptedLabel: "Accepté",
    trialDeclinedLabel: "Refusé",
    trialAcceptSuccess: "Demande d'essai acceptée !",
    trialDeclineSuccess: "Demande d'essai refusée.",

    // ScoutDashboard
    scoutDashboardTitle: "Tableau de Bord Recruteur",
    scoutDashboardDesc: "Gérez vos joueurs sauvegardés et vos demandes d'essais en cours.",
    favoritedPlayersTab: "Joueurs Favoris",
    trialRequestsTab: "Demandes d'Essais",
    mySavedPlayersTitle: "Mes Joueurs Sauvegardés",
    noFavoritesDesc: "Aucun joueur dans vos favoris. Parcourez la recherche pour en ajouter !",
    cityRegion: "Ville / Région",
    viewProfileButton: "Voir le profil",
    removeFavoriteTooltip: "Retirer des favoris",
    trialTrackingTitle: "Suivi des demandes d'essai envoyées",
    noSentTrials: "Vous n'avez envoyé aucune invitation d'essai pour le moment.",
    tableHeaderPlayer: "Joueur",
    tableHeaderPosition: "Poste",
    tableHeaderMessage: "Message envoyé",
    tableHeaderDate: "Date de la demande",
    tableHeaderStatus: "Statut",
    tableHeaderAction: "Action",
    statusPending: "En attente",
    statusAccepted: "Acceptée",
    statusRejected: "Refusée",

    // Positions (abbreviations to full names)
    pos_GK: "Gardien (GK)",
    pos_CB: "Défenseur Central (CB)",
    pos_LB: "Défenseur Gauche (LB)",
    pos_RB: "Défenseur Droit (RB)",
    pos_CDM: "Milieu Défensif (CDM)",
    pos_CM: "Milieu Central (CM)",
    pos_CAM: "Milieu Offensif (CAM)",
    pos_LW: "Ailier Gauche (LW)",
    pos_RW: "Ailier Droit (RW)",
    pos_ST: "Buteur (ST)",

    // Radar stat names
    radar_speed: "Vitesse",
    radar_technique: "Technique",
    radar_endurance: "Endurance",
    radar_passing: "Passe",
    radar_shooting: "Tir",
    radar_dribbling: "Dribble",
    radar_defending: "Défense",
    radar_physical: "Physique"
  },
  ar: {
    // Navbar
    discover: "استكشف",
    myProfile: "ملفي الشخصي",
    dashboard: "لوحة التحكم",
    logout: "تسجيل الخروج",
    login: "تسجيل الدخول",
    join: "انضم إلى Scoutini",
    player: "لاعب",
    scout: "منقب",
    club: "نادي",
    academy: "أكاديمية",
    admin: "مدير",
    
    // Home
    homePromo: "المنصة الأولى للتنقيب الرياضي في تونس",
    homeHeroStart: "كن النجم القادم في",
    homeHeroGreen: "كرة القدم التونسية",
    homeHeroDesc: "أنشئ سيرتك الذاتية الكروية الرقمية، وانشر مقاطع الفيديو الخاصة بك، واحصل على فرصة لاكتشافك من قبل أكبر الأندية والأكاديميات والكشافة في تونس.",
    homeSearchTalents: "البحث عن المواهب",
    homeWhyUse: "لماذا تستخدم Scoutini؟",
    
    homeFeature1Title: "سيرة ذاتية كروية رقمية",
    homeFeature1Desc: "أدخل مركزك، وقدمك المفضلة، ومقاييسك البدنية (الطول/الوزن) وإحصائياتك الرئيسية. سيرة ذاتية احترافية حقيقية متاحة بنقرة واحدة.",
    
    homeFeature2Title: "مقاطع فيديو المهارات",
    homeFeature2Desc: "ارفع أفضل لقطاتك، أهدافك، مراوغاتك وحصصك التدريبية لتظهر موهبتك وإمكانياتك بشكل ملموس.",
    
    homeFeature3Title: "تنقيب مباشر",
    homeFeature3Desc: "يقوم الكشافة والأكاديميات والأندية التونسية بإجراء عمليات بحث متقدمة بمعايير دقيقة لتقديم دعوات تجارب اختبار بدنية لك.",
    
    homeSectionTitle: "تقريب المواهب من الكشافة في تونس",
    homeSectionDesc: "سواء كنت من تونس، صفاقس، سوسة، بنزرت، نابل أو أي ولاية أخرى، تلغي Scoutini الحواجز الجغرافية وتمنحك فرصة متساوية لتحقيق مسيرة احترافية ناجحة.",
    
    homeSectionPoint1Title: "تونسية 100%",
    homeSectionPoint1Desc: "متوافقة تماماً مع المنظومة المحلية وأندية الرابطة الأولى والثانية في تونس.",
    
    homeSectionPoint2Title: "مقاطع فيديو بجودة عالية",
    homeSectionPoint2Desc: "مشغل فيديو حديث لتحليل فني دقيق لمستويات وأداء اللاعبين.",
    
    homeFooter: "© 2026 Scoutini TN. جميع الحقوق محفوظة. صمم خصيصاً لدعم كرة القدم التونسية.",
    
    ctaCreateCV: "أنشئ سيرتي الذاتية الكروية",
    ctaManageCV: "إدارة سيرتي الذاتية الكروية",
    ctaDashboard: "الولوج إلى لوحة التحكم",
    
    // Auth Pages & Compliance
    loginTitle: "تسجيل الدخول إلى Scoutini",
    registerTitle: "إنشاء حساب على Scoutini",
    registerSub: "اختر نوع حسابك وابدأ المغامرة",
    email: "البريد الإلكتروني",
    password: "كلمة المرور (6 أحرف على الأقل)",
    role: "أنا...",
    registerButton: "تسجيل",
    loginButton: "دخول",
    noAccount: "ليس لديك حساب؟ سجل الآن",
    haveAccount: "لديك حساب بالفعل؟ سجل دخولك",
    firstName: "الاسم الأول",
    lastName: "اللقب",
    fullName: "الاسم الكامل",
    organization: "اسم الهيكل أو النادي",
    dateOfBirth: "تاريخ الولادة",
    parentInfoTitle: "موافقة الوالدين (إلزامي للقصر)",
    parentName: "الاسم الكامل للولي / الوصي القانوني",
    parentNationalId: "رقم بطاقة التعريف الوطنية للولي",
    parentPhone: "رقم هاتف الولي",
    parentEmail: "البريد الإلكتروني للولي",
    parentalConsentCheck: "أؤكد تحت شرفي أن لدي موافقة والدي/ولي أمري القانوني للتسجيل ومشاركة معلوماتي.",
    termsCheck: "أوافق على شروط الاستخدام العامة وسياسة الخصوصية الخاصة بـ Scoutini.",
    acceptTermsStart: "أوافق على ",
    acceptTermsAnd: " و ",
    acceptTermsEnd: " الخاصة بـ Scoutini.",
    cguLinkText: "شروط الاستخدام العامة",
    privacyLinkText: "سياسة الخصوصية",
    cguContent: "<h3>1. القبول بالشروط</h3><p>بإنشاء حساب على Scoutini، فإنك توافق على الالتزام بشروط الاستخدام هذه. إذا كنت قاصراً يقل عمرك عن 18 عاماً، فإنك تؤكد أنك حصلت على موافقة صريحة من والدك أو ولي أمرك القانوني.</p><h3>2. حماية القصر</h3><p>أمان وحماية القصر هما جوهر منصة Scoutini. يُمنع منعاً باتاً على أي كشاف أو نادٍ أو أكاديمية محاولة الاتصال المباشر بوسائل خارجية أو غير لائقة مع لاعب قاصر. يجب أن تمر جميع طلبات تجارب الاختبار البدنية الرسمية إلزامياً عبر بيانات الولي المسجلة عند التسجيل.</p><h3>3. صحة المعلومات</h3><p>تتعهد بتقديم معلومات صحيحة (الهوية، الإحصائيات، تاريخ الميلاد). أي تصريح كاذب قد يؤدي إلى حذف حسابك فوراً.</p>",
    privacyContent: "<h3>1. البيانات التي نجمعها</h3><p>نجمع بيانات الهوية (الاسم، اللقب، البريد الإلكتروني، الهاتف)، بيانات الملف الشخصي (تاريخ الميلاد، الطول، الوزن، النادي الحالي)، وبالنسبة للاعبين القصر، بيانات الولي القانوني (الاسم، البريد الإلكتروني، الهاتف، رقم بطاقة التعريف الوطنية).</p><h3>2. الغرض من معالجة البيانات</h3><p>تُستخدم بيانات الولي واللاعبين فقط لضمان الامتثال القانوني وتأمين التواصل في إطار التنقيب عن المواهب. لا يتم مشاركة أي بيانات مع أطراف غير مصرح لها.</p><h3>3. حق الوصول والحذف</h3><p>وفقاً للقانون الأساسي عدد 63 لسنة 2004 في تونس، يحق للمستخدمين (وأوليائهم للقصر) الوصول إلى بياناتهم وتعديلها وحذفها بمجرد تقديم طلب.</p>",
    
    // General
    loading: "جاري التحميل...",
    back: "رجوع",
    save: "حفظ",
    cancel: "إلغاء",
    tunisia: "تونس",

    // Login
    welcomeBack: "مرحباً بعودتك!",
    loginSubtitle: "سجل الدخول للولوج إلى حساب Scoutini الخاص بك",
    emailField: "البريد الإلكتروني",
    passwordField: "كلمة المرور",
    placeholderEmail: "مثال: joueur@scoutini.tn",
    signUpFreeLink: "سجل مجاناً",
    invalidCredentialsError: "بيانات الدخول غير صحيحة.",
    dontHaveAccount: "ليس لديك حساب؟",
    alreadyHaveAccount: "لديك حساب بالفعل؟",
    loginLink: "تسجيل الدخول",

    // Register
    rolePlayerDesc: "إنشاء سيرة ذاتية",
    roleScoutDesc: "منقب محترف",
    roleClubDesc: "منقب نادٍ",
    roleAcademyDesc: "أكاديمية",
    placeholderFirstName: "مثال: أحمد",
    placeholderLastName: "مثال: بن سعيد",
    placeholderFullName: "مثال: محمد الغربي",
    placeholderOrganization: "مثال: شبان الترجي الرياضي",
    placeholderParentName: "مثال: الهادي الشريف",
    placeholderParentNationalId: "مثال: 08765432",
    placeholderParentPhone: "مثال: +216 98 765 432",
    placeholderParentEmail: "مثال: parent@email.com",
    placeholderEmailRegister: "مثال: contact@email.com",
    validationTermsError: "يجب عليك قبول شروط الاستخدام العامة وسياسة الخصوصية.",
    validationParentalError: "معلومات موافقة الولي وتأكيده إلزامية للاعبين القصر.",
    registerError: "خطأ أثناء التسجيل.",

    // SearchTalents
    searchTitle: "اكتشاف المواهب",
    searchSubtitle: "ابحث وصنف لاعبي كرة القدم الشباب في تونس حسب المركز، الولاية أو المهارات.",
    searchPlaceholderName: "ابحث باسم اللاعب...",
    searchButton: "بحث",
    filterPosition: "المركز",
    filterRegion: "الولاية",
    filterFoot: "القدم المفضلة",
    filterAllPositions: "كل المراكز",
    filterAllTunisia: "كل تونس",
    filterAll: "الكل",
    filterRightFoot: "يميني",
    filterLeftFoot: "يساري",
    filterBothFeet: "كلتا القدمين",
    resetFilters: "إعادة تعيين",
    noPlayersFound: "لم يتم العثور على أي لاعب",
    noPlayersFoundDesc: "حاول توسيع نطاق البحث الخاص بك.",
    freeAgent: "لاعب حر",
    statSpeed: "السرعة",
    statTechnique: "التقنية",
    viewCV: "عرض السيرة الذاتية",

    // PlayerProfile
    loginToFavorite: "يرجى تسجيل الدخول لإضافة هذا اللاعب إلى المفضلة.",
    inFavorites: "في المفضلة",
    addFavorite: "المفضلة",
    inviteToTrial: "دعوة لتجربة اختبار",
    bioAndPath: "السيرة الذاتية والمسار الكروي",
    noBio: "لم يكتب اللاعب سيرة ذاتية بعد.",
    measurementsTitle: "القياسات البدنية والمعلومات",
    height: "الطول",
    weight: "الوزن",
    preferredFoot: "القدم",
    nationality: "الجنسية",
    bothFeetLabel: "القدمين",
    rightFootLabel: "يمين",
    leftFootLabel: "يسار",
    bothFeetLabelLong: "يلعب بكلتا القدمين",
    rightFootLabelLong: "يميني",
    leftFootLabelLong: "يساري",
    noClub: "بدون نادٍ / حر",
    dateNotSpecified: "التاريخ غير محدد",
    statsOnField: "الإحصائيات في الملعب",
    matchesPlayed: "المباريات الملعوبة",
    goals: "الأهداف",
    assists: "التمريرات الحاسمة",
    performanceRadar: "مخطط الأداء",
    videosHighlightsTitle: "مقاطع فيديو المهارات واللقطات",
    noVideos: "لم ينشر هذا اللاعب أي مقطع فيديو للمهارات بعد.",
    invitePlayerTitle: "دعوة {name} لتجربة اختبار",
    invitePlayerDesc: "أرسل طلباً لتجربة اختبار بدنية أو حصة تدريبية. سيتلقى اللاعب رسالتك ويمكنه الرد عليها.",
    trialSentSuccess: "تم إرسال طلب تجربة الاختبار بنجاح!",
    playerNotified: "تم إشعار اللاعب.",
    invitationMessage: "رسالة الدعوة",
    invitationPlaceholder: "حدد التاريخ، المكان، وتفاصيل الاختبار (مثال: تجربة في تونس يوم 30 جوان)...",
    sendInvitation: "إرسال الدعوة",
    playerNotFound: "اللاعب غير موجود",
    playerNotFoundDesc: "الملف الشخصي لهذا اللاعب غير موجود أو تم حذفه.",
    backToSearch: "الالتحاق بالبحث",
    confirmRemoveFavorite: "هل تريد إزالة هذا اللاعب من المفضلة؟",

    // PlayerDashboard
    dashboardTitle: "لوحة تحكم اللاعب",
    profileResume: "ملخص الملف الشخصي",
    uploadPhoto: "رفع صورة",
    myDashboard: "لوحة التحكم",
    myFootballCV: "ملفي الشخصي",
    myStatistics: "إحصائياتي",
    highlightVideos: "مقاطع فيديو المهارات",
    trialRequests: "طلبات تجارب الاختبار",
    cvInfoTitle: "معلومات السيرة الذاتية الرياضية",
    firstNameLabel: "الاسم الأول",
    lastNameLabel: "اللقب",
    dobLabel: "تاريخ الميلاد",
    regionLabel: "الولاية",
    selectOption: "اختر",
    cityLabel: "المدينة / المعتمدية",
    cityPlaceholder: "مثال: المرسى / صفاقس الغربية",
    heightLabel: "الطول (سم)",
    heightPlaceholder: "مثال: 178",
    weightLabel: "الوزن (كغ)",
    weightPlaceholder: "مثال: 70",
    favPositionLabel: "المركز المفضل",
    preferredFootLabel: "القدم المفضلة",
    currentClubLabel: "النادي الحالي",
    currentClubPlaceholder: "مثال: شبان النادي الصفاقسي",
    contactPhoneLabel: "هاتف الاتصال",
    contactPhonePlaceholder: "مثال: +216 55 555 555",
    careerBioLabel: "المسار والنبذة الشخصية",
    careerBioPlaceholder: "تحدث عن مسيرتك الكروية، دوافعك...",
    saveCVButton: "حفظ السيرة الذاتية",
    skillsAndMatchesTitle: "القدرات والمباريات (الإحصائيات / 100)",
    physicalTechnicalTitle: "الجانب البدني والفني",
    attackingDefendingTitle: "الجانب الهجومي والدفاعي",
    matchStatsTitle: "الإحصائيات في المباريات",
    matchesPlayedLabel: "المباريات الملعوبة",
    goalsScoredLabel: "الأهداف المسجلة",
    assistsLabel: "التمريرات الحاسمة",
    updateStatsButton: "تحديث إحصائياتي",
    publishHighlightTitle: "نشر مقطع فيديو للمهارات",
    videoTitleLabel: "عنوان الفيديو",
    videoTitlePlaceholder: "مثال: هدف من مخالفة مباشرة",
    videoCategoryLabel: "الفئة",
    videoCategoryHIGHLIGHT: "لقطات عامة",
    videoCategoryMATCH: "مباراة كاملة / ملخص",
    videoCategoryTRAINING: "تدريبات / تمارين بدنية",
    videoCategorySKILLS: "مراوغات وفنيات",
    videoDescLabel: "الوصف / السياق",
    videoDescPlaceholder: "حدد على سبيل المثال دقيقة اللقطة، اسم الخصم...",
    videoFileLabel: "ملف الفيديو (MP4، حد أقصى 100 ميغا)",
    publishVideoButton: "نشر على Scoutini",
    myPublishedVideos: "مقاطع الفيديو الخاصة بي",
    noVideosPublished: "لم تنشر أي مقطع فيديو للمهارات بعد. أضف واحداً أعلاه!",
    deleteVideoConfirm: "هل تريد حقاً حذف هذا الفيديو؟",
    avatarSuccess: "تم تحديث صورة الملف الشخصي بنجاح!",
    cvSuccess: "تم تحديث السيرة الذاتية بنجاح!",
    statsSuccess: "تم حفظ إحصائيات الأداء!",
    videoSuccess: "تم نشر الفيديو بنجاح!",
    videoDeletedSuccess: "تم حذف الفيديو.",
    selectVideoFileError: "يرجى تحديد ملف فيديو.",
    receivedTrialsTitle: "طلبات تجارب الاختبار الواردة",
    noReceivedTrials: "لم تتلق أي طلب تجربة اختبار حتى الآن. أكمل ملفك وانشر مقاطع فيديو لجذب الانتباه!",
    scoutVerifiedLabel: "موثق",
    noPresentationMessage: "لا توجد رسالة تقديمية.",
    trialAcceptButton: "قبول",
    trialDeclineButton: "رفض",
    trialAcceptedLabel: "مقبول",
    trialDeclinedLabel: "مرفوض",
    trialAcceptSuccess: "تم قبول طلب التجربة بنجاح!",
    trialDeclineSuccess: "تم رفض طلب التجربة.",

    // ScoutDashboard
    scoutDashboardTitle: "لوحة تحكم المنقب",
    scoutDashboardDesc: "إدارة اللاعبين المحفوظين ومتابعة طلبات تجارب الاختبار الجارية.",
    favoritedPlayersTab: "اللاعبون المفضلون",
    trialRequestsTab: "طلبات تجارب الاختبار",
    mySavedPlayersTitle: "اللاعبون المحفوظون لدي",
    noFavoritesDesc: "لا يوجد أي لاعب في المفضلة. تصفح البحث لإضافة بعضهم!",
    cityRegion: "المدينة / الولاية",
    viewProfileButton: "عرض الملف الشخصي",
    removeFavoriteTooltip: "إزالة من المفضلة",
    trialTrackingTitle: "متابعة طلبات تجارب الاختبار المرسلة",
    noSentTrials: "لم ترسل أي دعوات لتجربة اختبار حالياً.",
    tableHeaderPlayer: "اللاعب",
    tableHeaderPosition: "المركز",
    tableHeaderMessage: "الرسالة المرسلة",
    tableHeaderDate: "تاريخ الطلب",
    tableHeaderStatus: "الحالة",
    tableHeaderAction: "الإجراء",
    statusPending: "في الانتظار",
    statusAccepted: "مقبولة",
    statusRejected: "مرفوضة",

    // Positions (abbreviations to full names)
    pos_GK: "حارس مرمى (GK)",
    pos_CB: "مدافع محوري (CB)",
    pos_LB: "ظهير أيسر (LB)",
    pos_RB: "ظهير أيمن (RB)",
    pos_CDM: "وسط دفاعي (CDM)",
    pos_CM: "وسط ميدان (CM)",
    pos_CAM: "وسط هجومي (CAM)",
    pos_LW: "جناح أيسر (LW)",
    pos_RW: "جناح أيمن (RW)",
    pos_ST: "مهاجم (ST)",

    // Radar stat names
    radar_speed: "السرعة",
    radar_technique: "التقنية",
    radar_endurance: "التحمل",
    radar_passing: "التمرير",
    radar_shooting: "التسديد",
    radar_dribbling: "المراوغة",
    radar_defending: "الدفاع",
    radar_physical: "البنية البدنية"
  },
  en: {
    // Navbar
    discover: "Discover",
    myProfile: "My Profile CV",
    dashboard: "Dashboard",
    logout: "Log Out",
    login: "Log In",
    join: "Join Scoutini",
    player: "Player",
    scout: "Scout",
    club: "Club",
    academy: "Academy",
    admin: "Admin",

    // Home
    homePromo: "Tunisia's #1 Football Scouting Platform",
    homeHeroStart: "Become the Next Star of",
    homeHeroGreen: "Tunisian Football",
    homeHeroDesc: "Create your digital football CV, upload your highlight videos and get spotted by the biggest clubs, academies and scouts in Tunisia.",
    homeSearchTalents: "Search Talents",
    homeWhyUse: "Why use Scoutini?",

    homeFeature1Title: "Digital Football CV",
    homeFeature1Desc: "Enter your position, preferred foot, measurements (height/weight) and key stats. A real professional CV accessible in one click.",

    homeFeature2Title: "Highlight Videos",
    homeFeature2Desc: "Upload your best moments, goals, dribbles and training sessions to concretely showcase your talent and skills.",

    homeFeature3Title: "Direct Scouting",
    homeFeature3Desc: "Tunisian scouts, academies and clubs run advanced searches with precise criteria to send you physical trial requests.",

    homeSectionTitle: "Connecting Talents with Scouts in Tunisia",
    homeSectionDesc: "Whether you're from Tunis, Sfax, Sousse, Bizerte, Nabeul or any other governorate, Scoutini removes geographic barriers and gives you an equal chance to build a professional career.",

    homeSectionPoint1Title: "100% Tunisian",
    homeSectionPoint1Desc: "Adapted to the local ecosystem and Ligue 1 & 2 clubs in Tunisia.",

    homeSectionPoint2Title: "Quality Videos",
    homeSectionPoint2Desc: "A modern video player to precisely analyze the technical profile of players.",

    homeFooter: "© 2026 Scoutini TN. All rights reserved. Designed to promote Tunisian football.",

    ctaCreateCV: "Create my Player CV",
    ctaManageCV: "Manage my Player CV",
    ctaDashboard: "Go to my Dashboard",

    // Auth Pages & Compliance
    loginTitle: "Log in to Scoutini",
    registerTitle: "Create a Scoutini account",
    registerSub: "Choose your profile and start the adventure",
    email: "Email Address",
    password: "Password (min 6 characters)",
    role: "I am a...",
    registerButton: "Sign Up",
    loginButton: "Log In",
    noAccount: "Don't have an account? Sign Up",
    haveAccount: "Already have an account? Log In",
    firstName: "First Name",
    lastName: "Last Name",
    fullName: "Full Name",
    organization: "Structure / Club Name",
    dateOfBirth: "Date of Birth",
    parentInfoTitle: "Parental Consent (Required for minors)",
    parentName: "Parent / Legal Guardian Full Name",
    parentNationalId: "Parent National ID Number (CIN)",
    parentPhone: "Parent Phone Number",
    parentEmail: "Parent Email Address",
    parentalConsentCheck: "I solemnly confirm that I have my parent/legal guardian's consent to sign up and share my information.",
    termsCheck: "I accept the Terms of Use and the Privacy Policy of Scoutini.",
    acceptTermsStart: "I accept the ",
    acceptTermsAnd: " and ",
    acceptTermsEnd: " of Scoutini.",
    cguLinkText: "Terms of Use",
    privacyLinkText: "Privacy Policy",
    cguContent: "<h3>1. Acceptance of Terms</h3><p>By creating an account on Scoutini, you agree to be bound by these Terms of Use. If you are under 18 years old, you declare that you have obtained the express consent of your parent or legal guardian.</p><h3>2. Protection of Minors</h3><p>The safety and protection of minors is at the core of Scoutini. It is strictly forbidden for any scout, club, or academy to attempt direct contact through external or inappropriate means with a minor. All official trial requests must go through the parent/guardian details provided during registration.</p><h3>3. Accuracy of Information</h3><p>You agree to provide true information (identity, statistics, date of birth). Any false statement may result in the immediate termination of your account.</p>",
    privacyContent: "<h3>1. Data Collected</h3><p>We collect identification data (first name, last name, email, phone), profile data (date of birth, height, weight, current club) and, for minor players, the coordinates of the legal guardian (name, email, phone, CIN card number).</p><h3>2. Purpose of Processing</h3><p>Parental and player data are only used to ensure legal compliance and secure connections within the framework of talent detection. No data is shared with unauthorized third parties.</p><h3>3. Right of Access and Deletion</h3><p>In accordance with Organic Law No. 2004-63 in Tunisia, users (and their parents if minor) have the right to access, rectify, and delete their data upon simple request.</p>",

    // General
    loading: "Loading...",
    back: "Back",
    save: "Save",
    cancel: "Cancel",
    tunisia: "Tunisia",

    // Login
    welcomeBack: "Welcome back!",
    loginSubtitle: "Log in to access your Scoutini account",
    emailField: "Email Address",
    passwordField: "Password",
    placeholderEmail: "Ex: player@scoutini.tn",
    signUpFreeLink: "Sign up for free",
    invalidCredentialsError: "Invalid credentials.",
    dontHaveAccount: "Don't have an account?",
    alreadyHaveAccount: "Already have an account?",
    loginLink: "Log In",

    // Register
    rolePlayerDesc: "Create my CV",
    roleScoutDesc: "Pro scout",
    roleClubDesc: "Club scout",
    roleAcademyDesc: "Academy",
    placeholderFirstName: "Ex: Ahmed",
    placeholderLastName: "Ex: Ben Said",
    placeholderFullName: "Ex: Mohamed Gharbi",
    placeholderOrganization: "Ex: Scoutini Pro / EST",
    placeholderParentName: "Ex: Hedi Cherif",
    placeholderParentNationalId: "Ex: 08765432",
    placeholderParentPhone: "Ex: +216 98 765 432",
    placeholderParentEmail: "Ex: parent@email.com",
    placeholderEmailRegister: "Ex: contact@email.com",
    validationTermsError: "You must accept the General Terms of Use and Privacy Policy.",
    validationParentalError: "Parental consent details and confirmation are mandatory for minor players.",
    registerError: "Error during registration.",

    // SearchTalents
    searchTitle: "Detect Talents",
    searchSubtitle: "Search and filter young football players in Tunisia by position, region, or skills.",
    searchPlaceholderName: "Search by player name...",
    searchButton: "Search",
    filterPosition: "Position",
    filterRegion: "Region (Governorate)",
    filterFoot: "Preferred Foot",
    filterAllPositions: "All positions",
    filterAllTunisia: "All Tunisia",
    filterAll: "All",
    filterRightFoot: "Right-footed",
    filterLeftFoot: "Left-footed",
    filterBothFeet: "Both feet",
    resetFilters: "Reset",
    noPlayersFound: "No players found",
    noPlayersFoundDesc: "Try broadening your search filters.",
    freeAgent: "Free Agent",
    statSpeed: "Speed",
    statTechnique: "Technique",
    viewCV: "View CV",

    // PlayerProfile
    loginToFavorite: "Please log in to add this player to favorites.",
    inFavorites: "In Favorites",
    addFavorite: "Favorite",
    inviteToTrial: "Invite to a trial",
    bioAndPath: "Biography & Career",
    noBio: "The player has not written a biography yet.",
    measurementsTitle: "Measurements & Info",
    height: "Height",
    weight: "Weight",
    preferredFoot: "Foot",
    nationality: "Nationality",
    bothFeetLabel: "Both",
    rightFootLabel: "Right",
    leftFootLabel: "Left",
    bothFeetLabelLong: "Ambidextrous",
    rightFootLabelLong: "Right-footed",
    leftFootLabelLong: "Left-footed",
    noClub: "Without club / Free",
    dateNotSpecified: "Date not specified",
    statsOnField: "On-field Statistics",
    matchesPlayed: "Matches played",
    goals: "Goals",
    assists: "Assists",
    performanceRadar: "Performance Radar",
    videosHighlightsTitle: "Highlight Videos & Compilations",
    noVideos: "No highlight videos published by this player.",
    invitePlayerTitle: "Invite {name} to a trial",
    invitePlayerDesc: "Send a physical trial or training request. The player will receive your message and can reply.",
    trialSentSuccess: "Trial request sent!",
    playerNotified: "The player has been notified.",
    invitationMessage: "Invitation message",
    invitationPlaceholder: "Specify the date, location, and details of the trial (e.g., trial in Tunis on June 30)...",
    sendInvitation: "Send invitation",
    playerNotFound: "Player not found",
    playerNotFoundDesc: "This player's profile does not exist or has been deleted.",
    backToSearch: "Back to Search",
    confirmRemoveFavorite: "Remove this player from your favorites?",

    // PlayerDashboard
    dashboardTitle: "Player Dashboard",
    profileResume: "Profile Summary",
    uploadPhoto: "Upload",
    myDashboard: "Dashboard",
    myFootballCV: "My Football CV",
    myStatistics: "My Statistics",
    highlightVideos: "Highlight Videos",
    trialRequests: "Trial Requests",
    cvInfoTitle: "Football CV Information",
    firstNameLabel: "First Name",
    lastNameLabel: "Last Name",
    dobLabel: "Date of Birth",
    regionLabel: "Governorate",
    selectOption: "Select",
    cityLabel: "City / Municipality",
    cityPlaceholder: "Ex: La Marsa / Sfax Ouest",
    heightLabel: "Height (cm)",
    heightPlaceholder: "Ex: 178",
    weightLabel: "Weight (kg)",
    weightPlaceholder: "Ex: 70",
    favPositionLabel: "Preferred Position",
    preferredFootLabel: "Preferred Foot",
    currentClubLabel: "Current Club",
    currentClubPlaceholder: "Ex: CSS Jeunes (or None)",
    contactPhoneLabel: "Contact Phone",
    contactPhonePlaceholder: "Ex: +216 55 555 555",
    careerBioLabel: "Career & Bio",
    careerBioPlaceholder: "Talk about your career path, your motivations...",
    saveCVButton: "Save CV",
    skillsAndMatchesTitle: "Abilities & Matches (Stats / 100)",
    physicalTechnicalTitle: "Physical & Technical Profile",
    attackingDefendingTitle: "Attacking & Defending Profile",
    matchStatsTitle: "Match Statistics",
    matchesPlayedLabel: "Matches played",
    goalsScoredLabel: "Goals scored",
    assistsLabel: "Assists",
    updateStatsButton: "Update my Stats",
    publishHighlightTitle: "Publish a Highlight Video",
    videoTitleLabel: "Video Title",
    videoTitlePlaceholder: "Ex: Direct free kick goal / Dribbles & Skills",
    videoCategoryLabel: "Category",
    videoCategoryHIGHLIGHT: "General Highlights (Actions)",
    videoCategoryMATCH: "Full Match / Summary",
    videoCategoryTRAINING: "Training / Physical Drills",
    videoCategorySKILLS: "Dribbles & Technical Skills",
    videoDescLabel: "Description / Context",
    videoDescPlaceholder: "Indicate for example the minute of the action, the opponent's name...",
    videoFileLabel: "Video File (MP4, Max 100 MB)",
    publishVideoButton: "Publish on Scoutini",
    myPublishedVideos: "My Published Videos",
    noVideosPublished: "You have not published any highlight videos yet. Add one above!",
    deleteVideoConfirm: "Are you sure you want to delete this highlight video?",
    avatarSuccess: "Profile picture updated successfully!",
    cvSuccess: "CV profile updated successfully!",
    statsSuccess: "Performance statistics saved!",
    videoSuccess: "Highlight video published!",
    videoDeletedSuccess: "Video deleted.",
    selectVideoFileError: "Please select a video file.",
    receivedTrialsTitle: "Received Trial Requests",
    noReceivedTrials: "You have not received any trial requests yet. Complete your profile and upload videos to get noticed!",
    scoutVerifiedLabel: "Verified",
    noPresentationMessage: "No introduction message.",
    trialAcceptButton: "Accept",
    trialDeclineButton: "Decline",
    trialAcceptedLabel: "Accepted",
    trialDeclinedLabel: "Declined",
    trialAcceptSuccess: "Trial request accepted!",
    trialDeclineSuccess: "Trial request declined.",

    // ScoutDashboard
    scoutDashboardTitle: "Scout Dashboard",
    scoutDashboardDesc: "Manage your saved players and trace ongoing trial requests.",
    favoritedPlayersTab: "Favorite Players",
    trialRequestsTab: "Trial Requests",
    mySavedPlayersTitle: "My Saved Players",
    noFavoritesDesc: "No players in your favorites. Browse search to add some!",
    cityRegion: "City / Region",
    viewProfileButton: "View profile",
    removeFavoriteTooltip: "Remove from favorites",
    trialTrackingTitle: "Sent Trial Requests Tracking",
    noSentTrials: "You have not sent any trial invitations yet.",
    tableHeaderPlayer: "Player",
    tableHeaderPosition: "Position",
    tableHeaderMessage: "Sent Message",
    tableHeaderDate: "Request Date",
    tableHeaderStatus: "Status",
    tableHeaderAction: "Action",
    statusPending: "Pending",
    statusAccepted: "Accepted",
    statusRejected: "Rejected",

    // Positions (abbreviations to full names)
    pos_GK: "Goalkeeper (GK)",
    pos_CB: "Center Back (CB)",
    pos_LB: "Left Back (LB)",
    pos_RB: "Right Back (RB)",
    pos_CDM: "Defensive Mid (CDM)",
    pos_CM: "Central Mid (CM)",
    pos_CAM: "Attacking Mid (CAM)",
    pos_LW: "Left Winger (LW)",
    pos_RW: "Right Winger (RW)",
    pos_ST: "Striker (ST)",

    // Radar stat names
    radar_speed: "Speed",
    radar_technique: "Technique",
    radar_endurance: "Endurance",
    radar_passing: "Passing",
    radar_shooting: "Shooting",
    radar_dribbling: "Dribbling",
    radar_defending: "Defending",
    radar_physical: "Physical"
  }
};

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    // Initialiser avec la langue du localStorage ou 'fr' par défaut
    return localStorage.getItem('scoutini_lang') || 'fr';
  });

  useEffect(() => {
    localStorage.setItem('scoutini_lang', language);
    // Changer l'attribut HTML dir pour le support RTL
    const htmlElement = document.documentElement;
    htmlElement.setAttribute('lang', language);
    if (language === 'ar') {
      htmlElement.setAttribute('dir', 'rtl');
      htmlElement.classList.add('rtl');
    } else {
      htmlElement.setAttribute('dir', 'ltr');
      htmlElement.classList.remove('rtl');
    }
  }, [language]);

  const t = (key) => {
    if (translations[language] && translations[language][key]) {
      return translations[language][key];
    }
    // Fallback à la clé ou à la traduction française
    return (translations['fr'] && translations['fr'][key]) || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
